---
title: "AI-05 self-project"
output: html_notebook
---


I. Prepare data:

1/ Load data file:
```{r}
genes <- read.csv("Ch10Ex11.csv", header = FALSE)
```

2/ Display data:
```{r}
print(genes)
```


II. Clustering (using correlation-based distances):

1/ Hierarchical clustering:

a/ Complete method 
```{r}
hc.complete <- hclust(as.dist(1 - cor(genes)), method = "complete")
plot(hc.complete)
```

b/ Single method:
```{r}
hc.single <- hclust(as.dist(1 - cor(genes)), method = "single")
plot(hc.single)
```

c/ Average method:
```{r}
hc.ave <- hclust(as.dist(1 - cor(genes)), method = "average")
plot(hc.ave)
```

d/ Ward method:
```{r}
hc.ave <- hclust(as.dist(1 - cor(genes)), method = "ward.D")
plot(hc.ave)
```


2/ k-means clustering:
```{r}
km.out <- kmeans(t(genes), 2, nstart = 20)
print(km.out$cluster)
```


III. Find out list of genes that differ the most between 2 groups

```{r}
pr.out <- prcomp(t(genes), scale=TRUE)
head(pr.out$rotation)
```

```{r}
total.load <- apply(pr.out$rotation, 1, sum)
index <- order(abs(total.load), decreasing = TRUE)
index[1:5]
```

